# Generated by Django 3.2.12 on 2022-06-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='status',
            field=models.CharField(blank=True, choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=50, null=True),
        ),
    ]
